# Generated by Django 3.2.9 on 2021-11-20 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_quesmodel_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='home.user')),
            ],
        ),
    ]
