# Generated by Django 3.2.9 on 2021-11-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_score_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
