# Generated by Django 3.2.9 on 2021-11-20 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='scores',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='home.user'),
        ),
    ]
